{
 "title": "ASGI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version,cluster)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\"},app)"
    }
   },
   {
    "name": "fulfillment_center",
    "label": "Fulfillment Center",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},fulfillment_center)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},tenant)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},component)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\", component=~\"$component\"},role)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"2.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"[0,1].*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"3.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"4.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"5.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(metrics_python_asgi_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(metrics_python_asgi_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(metrics_python_asgi_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(metrics_python_asgi_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"POD\", container!=\"\"}[$__rate_interval])\n    and on(pod)\n        topk(1, metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}) by (pod,)\n) by (pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{cluster=~\"$cluster\", container!=\"POD\", container!=\"\"}\n    and on(cluster, pod)\n        topk(1, metrics_python_asgi_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}) by (pod,)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_asgi_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "workers" } },
   "targets": [
    {
     "expr": "sum(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"asgi\", state=\"busy\"}) by (component)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request size by HTTP method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_asgi_request_size_bytes_sum{cluster=\"prod\"}[$__rate_interval])) by (method)\n/\nsum(rate(metrics_python_asgi_request_size_bytes_count{cluster=\"prod\"}[$__rate_interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response size by HTTP method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_asgi_response_size_bytes_sum{cluster=\"prod\"}[$__rate_interval])) by (method)\n/\nsum(rate(metrics_python_asgi_response_size_bytes_count{cluster=\"prod\"}[$__rate_interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request and response size by HTTP method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(rate(metrics_python_asgi_request_size_bytes_sum{cluster=\"prod\"}[$__rate_interval])) by (method)\n    or\n    sum(rate(metrics_python_asgi_response_size_bytes_sum{cluster=\"prod\"}[$__rate_interval])) by (method) * 0\n  )\n  +\n  sum(rate(metrics_python_asgi_response_size_bytes_sum{cluster=\"prod\"}[$__rate_interval])) by (method)\n)\n/\nsum(rate(metrics_python_asgi_response_size_bytes_count{cluster=\"prod\"}[$__rate_interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}