{
 "title": "Celery",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version,cluster)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\"},app)"
    }
   },
   {
    "name": "fulfillment_center",
    "label": "Fulfillment Center",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},fulfillment_center)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},tenant)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},component)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\", component=~\"$component\"},role)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "0.5" }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "Celery workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"celery\", state=\"idle\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"celery\"}) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failed or retried tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(metrics_python_celery_task_execution_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", state!=\"SUCCESS\"}[$__rate_interval])) by (task, state)",
     "legendFormat": "{{task}} - {{state}}"
    }
   ]
  },
  {
   "title": "Task processing delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(metrics_python_celery_task_execution_delay_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le, queue))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container!=\"POD\", container!=\"\"}[$__rate_interval])\n    and on(pod)\n        topk(1, metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\",worker_type=\"celery\"}) by (pod,)\n) by (pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executed tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(metrics_python_celery_task_execution_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (queue,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed tasks by name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(metrics_python_celery_task_execution_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (task,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task execution duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(metrics_python_celery_task_execution_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le, task))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"POD\", container!=\"\"}\n    and on(cluster, pod)\n        topk(1, metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\",worker_type=\"celery\"}) by (pod,)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Published tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_celery_task_published_total{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (routing_key,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apply task duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(metrics_python_celery_task_apply_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le, task))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow tasks",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(metrics_python_celery_task_execution_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__range])) by (le, task))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent on tasks",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(metrics_python_celery_task_execution_duration_seconds_sum{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__range])) by (task,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task processing delay heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_celery_task_execution_delay_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task execution duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_celery_task_execution_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Celery worker busy ratio (pessimistic, based on samples at scrape time)",
   "type": "timeseries",
   "description": "Measured directly by sampling at scrape time. Maxed over 5 minutes of data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (role) (max_over_time(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"celery\", state=\"busy\"}[5m]))\n/\nsum by (role) (max_over_time(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"celery\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Celery worker-seconds/sec (measured at task finish)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "workers" } },
   "targets": [
    {
     "expr": "sum by (role)(rate(metrics_python_celery_task_execution_duration_seconds_sum{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}