{
 "title": "Django / Cache",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version,cluster)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\"},app)"
    }
   },
   {
    "name": "fulfillment_center",
    "label": "Fulfillment Center",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},fulfillment_center)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},tenant)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},component)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\", component=~\"$component\"},role)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "0.95" }
  ]
 },
 "panels": [
  {
   "title": "Cache operations by method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_django_cache_call_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (alias, method)",
     "legendFormat": "{{alias}} - {{method}}"
    }
   ]
  },
  {
   "title": "Time spent on cache operations by mehod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(metrics_python_django_cache_call_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le, alias, method))",
     "legendFormat": "{{alias}} - {{method}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_django_cache_call_gets_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", hit=\"True\"}[$__rate_interval])) by (alias, method)\n/\nsum(rate(metrics_python_django_cache_call_gets_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (alias, method)",
     "legendFormat": "{{alias}} - {{method}}"
    }
   ]
  },
  {
   "title": "Cache call heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_django_cache_call_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}