{
 "title": "Django / Middleware",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version,cluster)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\"},app)"
    }
   },
   {
    "name": "fulfillment_center",
    "label": "Fulfillment Center",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},fulfillment_center)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},tenant)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},component)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\", component=~\"$component\"},role)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "0.95" }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "Middleware processing duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(metrics_python_django_middleware_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le, middleware, method))",
     "legendFormat": "{{middleware}}.{{method}}"
    }
   ]
  },
  {
   "title": "Middleware execution duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_django_middleware_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Middleware calls",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_django_middleware_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (middleware, method)",
     "legendFormat": "{{middleware}}.{{method}}"
    }
   ]
  },
  {
   "title": "Time spent on middleware",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(metrics_python_django_middleware_duration_seconds_sum{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__range])) by (middleware,method)",
     "legendFormat": "{{middleware}}.{{method}}"
    }
   ]
  }
 ]
}