{
 "title": "Gunicorn",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version,cluster)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\"},app)"
    }
   },
   {
    "name": "fulfillment_center",
    "label": "Fulfillment Center",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},fulfillment_center)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},tenant)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\"},component)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(metrics_python_generics_info_application_version{cluster=~\"$cluster\", app=~\"$app\", component=~\"$component\"},role)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "app" },
  {
   "title": "Gunicorn workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"gunicorn\", state=\"idle\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"gunicorn\"}) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Log messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_gunicorn_log_records_total{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (level,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container!=\"POD\", container!=\"\"}[$__rate_interval])\n    and on(pod)\n        topk(1, metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\",worker_type=\"gunicorn\"}) by (pod,)\n) by (pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"2.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"[0,1].*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"3.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"4.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", status=~\"5.*\"}[$__rate_interval])) by (status,)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(metrics_python_gunicorn_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(metrics_python_gunicorn_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(metrics_python_gunicorn_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(metrics_python_gunicorn_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"POD\", container!=\"\"}\n    and on(cluster, pod)\n        topk(1, metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\",worker_type=\"gunicorn\"}) by (pod,)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_count{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(metrics_python_gunicorn_request_duration_seconds_bucket{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Gunicorn worker busy ratio (pessimistic, based on samples at scrape time)",
   "type": "timeseries",
   "description": "Measured directly by sampling at scrape time. Maxed over 5 minutes of data.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (role) (max_over_time(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"gunicorn\", state=\"busy\"}[5m]))\n/\nsum by (role) (max_over_time(metrics_python_generics_workers_workers_by_state{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", worker_type=\"gunicorn\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gunicorn worker-seconds/sec (measured at request finish)",
   "type": "timeseries",
   "description": "I.e. how many workers were on average fully saturated. (Note that there are multiple workers to a pod.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "processes" } },
   "targets": [
    {
     "expr": "sum by (role)(rate(metrics_python_gunicorn_request_duration_seconds_sum{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gunicorn worker busyness ratio (measured at request finish)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (role)(rate(metrics_python_gunicorn_request_duration_seconds_sum{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"}[2m]))\n  /\nsum by (role)(metrics_python_gunicorn_workers{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gunicorn worker deaths",
   "type": "timeseries",
   "description": "Based on critical log lines.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(metrics_python_gunicorn_log_records_total{cluster=~\"$cluster\", app=~\"$app\", fulfillment_center=~\"$fulfillment_center\", tenant=~\"$tenant\", component=~\"$component\", role=~\"$role\", level=\"critical\"}[$__rate_interval])) by (pod,)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}